name: Generar documentació

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositori
        uses: actions/checkout@v4

      - name: Donar permisos al script
        run: chmod +x scripts/generar_doc.sh

      - name: Generar documentació
        run: ./scripts/generar_doc.sh

      - name: Pujar canvis
        run: |
          git add README.md
          git commit -m "Actualitzar documentació automàtica" || echo "Sense canvis"
          git push
